### ISSUE TITLE
Unintended Overflow-Y

### ISSUE THREAD

**Issue by MJClement** [MJClement/itsoktobe#1]
Hi Sarah & Elly,
I have run into an issue with my repo regarding my overflow: scroll. I. have nearly completed my webpage minus the change on click js which i will get your help with next week, but for some reason my background overflow is much longer then my content and i cannot figure out which element is causing the ba

ckground to extend so far.

Would you be able to help me with this?  

attached is an image to show the extra spacing on the "glasses" tab.

<img width="1633" alt="Screen Shot 2019-10-12 at 2 15 33 PM" src="https://user-images.githubusercontent.com/43526538/66692528-c7877300-ecfb-11e9-9da5-5ac73fc0f3e1.png">

**Comment by jamesschoch** [comment]
It looks like because the elements are relatively positioned, they're not being removed from the flow of the page. So the pages height is extended as it's filled with items that have been moved visually but stay where they are. I think changing the position of the elements under the `<article>` tag to absolute and styling with {top:x;left:y;} might help fix it.

**Comment by MJClement** [comment]
*** UPDATE *** 
I officially feel like a cabbage, i asked multiple people for help and did hours or research trying to find a solution, i added a bunch of picture elements to help fill the space and have just come to the realisation that i simply could've simply changed the text element to absolute. ALL FIXED. Thanks

**Comment by sehsarah** [comment]
Sounds like you can close this issue since it's resolved @MJClement 👍 awesome work - thanks @jamesschoch
