### ISSUE TITLE
Javascript - on click of arrow, change the Image/Text/Signature to new content

### ISSUE THREAD

**Issue by MJClement** [MJClement/itsoktobe#2]
My website i nearly complete with exception to the JS. i cannot figure out how to do onclick changes and was wondering if i could get some help in class. I want to be able to click the arrow buttons and when i do it instantly changes the image, name, subname, description, signature and the body text to be a new person. I have 3-5 examples for each page but cannot figure out how to do this. 

I am just submitting an issue so that in class i could get some help with this. Thank You !!!

<img width="1746" alt="Screen Shot 2019-10-12 at 7 23 18 PM" src="https://user-images.githubusercontent.com/43526538/66696169-1b0eb680-ed26-11e9-9237-ca2aa3ceed1d.png">

**Comment by sehsarah** [comment]
Sweet. Writing out an idea -

Are those 4 elements within one container? Potentially named "slide" ...
This one could be `class="ok-slide ok-slide--1"` which is the John Lennon slide

So 
- there's one main outer "slider" container (`ok-slider`)
- all the "slides" would be present within that (as well as the left/right arrows)
- when u click a left/right arrow a class toggles on the outer container
- Using CSS you determine which slide to show, e.g. 
    - when `ok-slider--show-1` is present, you would display `ok-slide--1` and hide `ok-slide--2` and so on
    - when `ok-slider--show-2` is present, you would display `ok-slide--2` and hide `ok-slide--1` and so on

@MJClement can you add @ellysmlly ? We can check with her if she's used this method before or recommends something else. Not sure how best practice it is but simple...

Markup something like this -
```
<div class="ok-slider ok-slider--show-1">
    <div class="ok-arrow ok-arrow--left"></div>
   <div class="ok-arrow ok-arrow--right"></div>
    <div class="ok-slide ok-slide--1">
       // stuff for this slide in here
    </div>
    <div class="ok-slide ok-slide--2"></div>
    <div class="ok-slide ok-slide--3"></div>
    <div class="ok-slide ok-slide--4"></div>
</div>
```

SCSS something like -
```
.ok-slider--show-1 {
    .ok-slide--1 {
      display: block;
    }
    .ok-slide--2,
    .ok-slide--3,
    .ok-slide--4 {
      display: none;
   }
}
```

JS something like -
```
// Start at slide index 1 to start at the John Lennon slide
var $slideIndex = 1;

// When user clicks on the right arrow
$('ok-arrow--right').on('click', function (event) {
    // Remove current index class
    $('ok-slider').removeClass('ok-slider--show-' + $slideIndex);

    // Add next index class
    $slideIndex = $slideIndex+1;
    $('ok-slider').addClass('ok-slider--show-' + $slideIndex);
});
```

Then left would be `$slideIndex-1` instead of `$slideIndex+1` - but you'll also need some logic for when index is 0 or $lastIndex (i.e. you could either loop or stop at first slide when going left etc)

See how you go 👍

**Comment by sehsarah** [comment]
Also updated your Issue title to describe the particular issue you're solving

**Comment by MJClement** [comment]
Thank you @sehsarah, i will see if i can implement this tonight, otherwise i will speak with Elly in class and see what her recommendations are. 🙂
